---
stages:
  - build
  - package
  - deploy
build:
  image: golang:latest
  stage: build
  script:
    - apt update
    - ln -s /builds /go/src/gitlab.in2p3.fr
    - cd /go/src/gitlab.in2p3.fr/cc-in2p3-system/sequence
    - find . -name \*.go -exec sed -i 's:^\t"sequence:\t"gitlab.in2p3.fr/cc-in2p3-system/sequence:g' {} \;
    - sed -i '/^database =/c\database = "/var/lib/sequence/sequence.sdb"' sequence.toml
    - go get -t -d -v
    - go build --ldflags "-X gitlab.in2p3.fr/cc-in2p3-system/sequence.Version=$(git describe --always --tags HEAD)"
    - 'go test || :'
    - sed -e "s/__CREDENTIALS__/gitlab-ci-token:${CI_BUILD_TOKEN}/" .gitlab-ci-godeps-config > ~/.gitconfig
    - cd $CI_PROJECT_DIR/syslog_ng/cmd
    - 'go get -t -d -v || :'
    - go build --ldflags "-X gitlab.in2p3.fr/cc-in2p3-system/sequence.Version=$(git describe --always --tags HEAD)" syslog_ng_main.go
  artifacts:
    expire_in: '1 hour'
    paths:
      - syslog_ng/cmd
      - sequence.toml
package:
  image: gitlab-registry.in2p3.fr/cc-in2p3/docker-fpm:latest
  stage: package
  script:
    - find
    - mkdir -p usr/bin
    - mkdir -p var/lib/sequence
    - mkdir -p etc/sequence
    - mv sequence.toml custom_parser.toml ./etc/sequence/
    - mv syslog_ng/cmd/syslog_ng_main ./usr/bin/sequence-syslog_ng
    - fpm -s dir -t rpm --license "CECILL-B" --no-rpm-autoreqprov -n "sequence" -v "$(git describe --always --tags HEAD | sed s/^v//)" --url "https://gitlab.in2p3.fr/cc-in2p3-system/sequence" --description "high performance sequential log scanner, analyzer and parser" --maintainer "Fabien Wernli <wernli@in2p3.fr>" ./usr ./var ./etc
  dependencies:
    - build
  artifacts:
    expire_in: '1 hour'
    paths:
      - "*.rpm"
deploy:
  image: gitlab-registry.in2p3.fr/cc-in2p3/gitlab-ci-ccin2p3-docker-images:pulp-admin
  stage: deploy
  only:
    - tags
  script:
    - 'mkdir -m 0700 -p /root/.pulp && echo -e "${PULP_CREDENTIALS}" >/root/.pulp/user-cert.pem'
    - 'mkdir -p rpm && cp *.rpm rpm/'
    - 'pulp-admin rpm repo uploads rpm --dir rpm --repo-id cc6'
    - 'pulp-admin rpm repo publish run --repo-id cc6'
    - 'pulp-admin rpm repo uploads rpm --dir rpm --repo-id cc7'
    - 'pulp-admin rpm repo publish run --repo-id cc7'
  dependencies:
    - package
