---
stages:
  - build
  - package
  - deploy
build:
  image: golang:latest
  stage: build
  variables:
    LDFLAGS: -linkmode external -extldflags -static
  script:
    - apt update
    - sed -i '/^connectioninfo =/c\connectioninfo = "/var/lib/sequence/sequence.sdb"' sequence.toml
    - go get -d -v
    - go build --ldflags "-X gitlab.in2p3.fr/cc-in2p3-system/sequence.Version=$(git describe --always --tags HEAD) $LDFLAGS"
    - 'go test || :'
    - sed -e "s/__CREDENTIALS__/gitlab-ci-token:${CI_BUILD_TOKEN}/" .gitlab-ci-godeps-config > ~/.gitconfig
    - cd $CI_PROJECT_DIR/cmd/sequence_db
    - go get -d -v
    - go build --ldflags "-X gitlab.in2p3.fr/cc-in2p3-system/sequence.Version=$(git describe --always --tags HEAD) $LDFLAGS" sequence_db_main.go
  artifacts:
    expire_in: '1 hour'
    paths:
      - cmd/sequence_db
      - sequence.toml
package:
  image: gitlab-registry.in2p3.fr/cc-in2p3/docker-fpm:latest
  stage: package
  script:
    - find
    - mkdir -p usr/bin
    - mkdir -p var/lib/sequence
    - mkdir -p etc/sequence
    - mv sequence.toml ./etc/sequence/
    - mv cmd/sequence_db/sequence_db_main ./usr/bin/sequence-syslog_ng
    - fpm -s dir -t rpm --license "CECILL-B" --no-rpm-autoreqprov -n "sequence" -v "$(git describe --always --tags HEAD | sed s/^v//)" --url "https://gitlab.in2p3.fr/cc-in2p3-system/sequence" --description "high performance sequential log scanner, analyzer and parser" --maintainer "Fabien Wernli <wernli@in2p3.fr>" ./usr ./var ./etc
  dependencies:
    - build
  artifacts:
    expire_in: '1 hour'
    paths:
      - "*.rpm"
deploy:
  image: gitlab-registry.in2p3.fr/cc-in2p3/gitlab-ci-ccin2p3-docker-images:pulp-admin
  stage: deploy
  only:
    - tags
  script:
    - 'mkdir -m 0700 -p /root/.pulp && echo -e "${PULP_CREDENTIALS}" >/root/.pulp/user-cert.pem'
    - 'mkdir -p rpm && cp *.rpm rpm/'
    - 'pulp-admin rpm repo uploads rpm --dir rpm --repo-id cc6'
    - 'pulp-admin rpm repo publish run --repo-id cc6'
    - 'pulp-admin rpm repo uploads rpm --dir rpm --repo-id cc7'
    - 'pulp-admin rpm repo publish run --repo-id cc7'
  dependencies:
    - package
