
[tags]
    [tags.general]
    "%srcemail%"	=   "@EMAIL:srcemail:@"
    "%float%"		=   "@FLOAT@"
    "%integer%"		= 	"@NUMBER@"
    "%integer%:"	= 	"@NUMBER@:"
    "(%integer%)"	=	"(@NUMBER@)"
    "'%integer%'"	=   "'@NUMBER@'"
    "%srcip%"		=   "@IPvANY:srcip@"
    "%srcip%,"		=   "@IPvANY:srcip@,"
    "%dstip%"		=   "@IPvANY:dstip@"
    "%ipv6%"		=   "@IPv6:srcip@"
    "%srchost%" 	=	"@HOSTNAME:srchost@"
    "%srcport%" 	= 	"@NUMBER:srcport@"
    "%srcport%:" 	= 	"@NUMBER:srcport@:"
    "%srcmac%" 		= 	"@MACADDR:srcmac@"
    "%dsthost%" 	= 	"@HOSTNAME:dsthost:@"
    "%dstport%" 	= 	"@NUMBER:dstport@"
    "%dstmac%" 		= 	"@MACADDR:dstmac@"
    "%regextime%"	=	"@PCRE:timestamp:[regexnotfound]@"
	"%string%"	    =   "@ESTRING:: @"           #string types with fieldname
	"%alphanum%"	=   "@ESTRING:alphanum: @"
	"%path%"		=   "@ESTRING:path: @"
	"%id%"			=   "@ESTRING:id: @"
	"%msgtime%"		= 	"@ESTRING:msgtime: @"
	"%time%"		=	"@ESTRING:time: @"
	"%protocol%"	=	"@ESTRING:protocol: @"
	"%msgid%" 		=   "@ESTRING:msgid: @"
	"%severity%" 	=	"@ESTRING:severity: @"
	"%priority%" 	=	"@ESTRING:priority: @"
	"%apphost%" 	=	"@ESTRING:apphost: @"
	"%appip%" 		=   "@ESTRING:appip: @"
	"%appvendor%"	=	"@ESTRING:appvendor: @"
	"%appname%" 	=	"@ESTRING:appname: @"
	"%srcdomain%"	=	"@ESTRING:srcdomain: @"
	"%srczone%" 	= 	"@ESTRING:srczone: @"
	"%srcipnat%" 	=	"@ESTRING:srcipnat: @"
	"%srcportnat%" 	= 	"@ESTRING:srcportnat: @"
	"%srcuser%" 	=  	"@ESTRING:srcuser: @"
	"%srcuid%" 		=  	"@ESTRING:srcuid: @"
	"%srcgid%" 		=  	"@ESTRING:srcgid: @"
	"%dstdomain%" 	= 	"@ESTRING:dstdomain: @"
	"%dstzone%" 	=	"@ESTRING:dstzone: @"
	"%dstipnat%" 	= 	"@ESTRING:dstipnat: @"
	"%dstportnat%" 	= 	"@ESTRING:dstportnat: @"
	"%dstuser%" 	= 	"@ESTRING:dstuser: @"
	"%dstuid%" 		= 	"@ESTRING:dstuid: @"
	"%dstgroup%" 	= 	"@ESTRING:dstgroup: @"
	"%dstgid%" 		= 	"@ESTRING:dstgid: @"
	"%dstemail%" 	= 	"@ESTRING:dstemail: @"
	"%iniface%" 	= 	"@ESTRING:iniface: @"
	"%outiface%" 	= 	"@ESTRING:outiface: @"
	"%policyid%" 	= 	"@ESTRING:policyid: @"
	"%sessionid%" 	= 	"@ESTRING:sessionid: @"
	"%action%" 		= 	"@ESTRING:action: @"
	"%command%" 	= 	"@ESTRING:command: @"
	"%object%" 		= 	"@ESTRING:object: @"
	"%method%" 		= 	"@ESTRING:method: @"
	"%status%" 		= 	"@ESTRING:status: @"
	"%reason%" 		= 	"@ESTRING:reason: @"
	"%bytesrecv%" 	= 	"@ESTRING:bytesrecv: @"
	"%bytessent%" 	= 	"@ESTRING:bytessent: @"
	"%pktsrecv%" 	= 	"@ESTRING:pktsrecv: @"
	"%pktssent%" 	= 	"@ESTRING:pktssent: @"
	"%duration%" 	= 	"@ESTRING:duration: @"
	"%uri%"			=	"@ESTRING:uri: @"

	[tags.delimitedstring]
	"()"		= 	"@QSTRING:[fieldname]:()@"
    "[]"		= 	"@QSTRING:[fieldname]:[]@"
    "\"\""		= 	"@QSTRING:[fieldname]:\"@"
    "''"		= 	"@QSTRING:[fieldname]:'@"
    "<>"		=	"@QSTRING:[fieldname]:<>@"
    "``"		=	"@QSTRING:[fieldname]:`@"
    ":"			=	"@ESTRING:[fieldname]::@"
    ","			=	"@ESTRING:[fieldname]:,@"
    ";"			=	"@ESTRING:[fieldname]:;@"
    ">"			=	"@ESTRING:[fieldname]:>@"
    "'"			=	"@ESTRING:[fieldname]:'@"
    "no-sp"		=	"@ESTRING:[fieldname]:@"
    "default"   =   "@ESTRING:[fieldname]: @"
	
	#only need to add the tags here that you wish to change the name of, otherwise the sequence value is used.
	[tags.fieldname]
	"msgtime"	    =   "timestamp"
	"action"	    =   "action-test"
	
