
[tags]
    [tags.general]
    "%multiline%"   =   "@ANYSTRING:[fieldname]@"
    "%srcemail%"	=   "@EMAIL:[fieldname]:@"
    "%float%"		=   "@FLOAT:[fieldname]@"
    "%integer%"		= 	"@NUMBER:[fieldname]@"
    "%srcip%"		=   "@IPvANY:[fieldname]@"
    "%dstip%"		=   "@IPvANY:[fieldname]@"
    "%ipv6%"		=   "@IPv6:[fieldname]@"
    "%srchost%" 	=	"@HOSTNAME:[fieldname]@"
    "%srcport%" 	= 	"@NUMBER:[fieldname]@"
    "%srcmac%" 		= 	"@MACADDR:[fieldname]@"
    "%dsthost%" 	= 	"@HOSTNAME:[fieldname]:@"
    "%dstport%" 	= 	"@NUMBER:[fieldname]@"
    "%dstmac%" 		= 	"@MACADDR:[fieldname]@"
    "%regextime%"	=	"@PCRE:timestamp:[regexnotfound]@"
	"%string%"	    =   "@ESTRING:[fieldname]: @"           #string types with fieldname
	"%alphanum%"	=   "@ESTRING:[fieldname]: @"
	"%id%"			=   "@ESTRING:[fieldname]: @"
	"%msgtime%"		= 	"@ESTRING:[fieldname]: @"
	"%time%"		=	"@ESTRING:[fieldname]: @"
	"%protocol%"	=	"@ESTRING:[fieldname]: @"
	"%msgid%" 		=   "@ESTRING:[fieldname]: @"
	"%severity%" 	=	"@ESTRING:[fieldname]: @"
	"%priority%" 	=	"@ESTRING:[fieldname]: @"
	"%apphost%" 	=	"@ESTRING:[fieldname]: @"
	"%appip%" 		=   "@ESTRING:[fieldname]: @"
	"%appvendor%"	=	"@ESTRING:[fieldname]: @"
	"%appname%" 	=	"@ESTRING:[fieldname]: @"
	"%srcdomain%"	=	"@ESTRING:[fieldname]: @"
	"%srczone%" 	= 	"@ESTRING:[fieldname]: @"
	"%srcipnat%" 	=	"@ESTRING:[fieldname]: @"
	"%srcportnat%" 	= 	"@ESTRING:[fieldname]: @"
	"%srcuser%" 	=  	"@ESTRING:[fieldname]: @"
	"%srcuid%" 		=  	"@ESTRING:[fieldname]: @"
	"%srcuri%" 		=  	"@ESTRING:[fieldname]: @"
	"%srcgid%" 		=  	"@ESTRING:[fieldname]: @"
	"%dstdomain%" 	= 	"@ESTRING:[fieldname]: @"
	"%dstzone%" 	=	"@ESTRING:[fieldname]: @"
	"%dstipnat%" 	= 	"@ESTRING:[fieldname]: @"
	"%dstportnat%" 	= 	"@ESTRING:[fieldname]: @"
	"%dstuser%" 	= 	"@ESTRING:[fieldname]: @"
	"%dstuid%" 		= 	"@ESTRING:[fieldname]: @"
	"%dsturi%" 		=  	"@ESTRING:[fieldname]: @"
	"%dstgroup%" 	= 	"@ESTRING:[fieldname]: @"
	"%dstgid%" 		= 	"@ESTRING:[fieldname]: @"
	"%dstemail%" 	= 	"@ESTRING:[fieldname]: @"
	"%iniface%" 	= 	"@ESTRING:[fieldname]: @"
	"%outiface%" 	= 	"@ESTRING:[fieldname]: @"
	"%policyid%" 	= 	"@ESTRING:[fieldname]: @"
	"%sessionid%" 	= 	"@ESTRING:[fieldname]: @"
	"%action%" 		= 	"@ESTRING:[fieldname]: @"
	"%command%" 	= 	"@ESTRING:[fieldname]: @"
	"%object%" 		= 	"@ESTRING:[fieldname]: @"
	"%method%" 		= 	"@ESTRING:[fieldname]: @"
	"%status%" 		= 	"@ESTRING:[fieldname]: @"
	"%reason%" 		= 	"@ESTRING:[fieldname]: @"
	"%bytesrecv%" 	= 	"@ESTRING:[fieldname]: @"
	"%bytessent%" 	= 	"@ESTRING:[fieldname]: @"
	"%pktsrecv%" 	= 	"@ESTRING:[fieldname]: @"
	"%pktssent%" 	= 	"@ESTRING:[fieldname]: @"
	"%duration%" 	= 	"@ESTRING:[fieldname]: @"
	"%uri%"			=	"@ESTRING:[fieldname]: @"

	[tags.delimitedstring]
	"()"		= 	"@QSTRING:[fieldname]:()@"
    "[]"		= 	"@QSTRING:[fieldname]:[]@"
    "\"\""		= 	"@QSTRING:[fieldname]:\"@"
    "''"		= 	"@QSTRING:[fieldname]:'@"
    "<>"		=	"@QSTRING:[fieldname]:<>@"
    "``"		=	"@QSTRING:[fieldname]:`@"
    ":"			=	"@ESTRING:[fieldname]::@"
    ","			=	"@ESTRING:[fieldname]:,@"
    ";"			=	"@ESTRING:[fieldname]:;@"
    ">"			=	"@ESTRING:[fieldname]:>@"
    "'"			=	"@ESTRING:[fieldname]:'@"
    "?"			=	"@ESTRING:[fieldname]:?@"
    "&"			=	"@ESTRING:[fieldname]:&@"
    "no-sp"		=	"@ESTRING:[fieldname]:@"
    "default"   =   "@ESTRING:[fieldname]: @"
	
	#only need to add the tags here that you wish to change the name of, otherwise the sequence value is used.
	[tags.fieldname]
	"msgtime"	    =   "timestamp"
	"action"        =   "action-test"
	"float"         =   "decimal"
	
