[sqlite3]
	dbname = "sequence.sdb"

[psql]
  dbname = "Sequence"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "password"
  schema = "public"
  sslmode = "disable"
  blacklist = ["migrations", "other"]

[mysql]
  dbname  = "dbname"
  host    = "localhost"
  port    = 3306
  user    = "dbusername"
  pass    = "dbpassword"
  sslmode = "false"

[mssql]
  dbname  = "Sequence"
  host    = "localhost/SQLEXPRESS2014"
  port    = 1433
  user    = "sa"
  pass    = "admin"
  sslmode = "disable"
  schema  = "dbo"