
[tags]
    [tags.general]
    "%multiline%"   =   "%{GREEDYDATA:[fieldname]}"
    "%srcemail%"	=   "%{EMAILADDRESS:[fieldname]}"
    "%float%"		=   "%{BASE16FLOAT:[fieldname]}"
    "%integer%"		= 	"%{INT:[fieldname]}"
    "%srcip%"		=   "%{IP:[fieldname]}"
    "%dstip%"		=   "%{IP:[fieldname]}"
    "%ipv6%"		=   "%{IP:[fieldname]}"
    "%srchost%" 	=	"%{HOSTNAME:[fieldname]}"
    "%srcport%" 	= 	"%{INT:[fieldname]}"
    "%srcmac%" 		= 	"%{MAC:[fieldname]}"
    "%dsthost%" 	= 	"%{HOSTNAME:[fieldname]}"
    "%dstport%" 	= 	"%{INT:[fieldname]}"
    "%dstmac%" 		= 	"%{MAC:[fieldname]}"
    "%regextime%"	=	"%{DATA:[fieldname]}"
	"%string%"	    =   "%{DATA:[fieldname]}"        
	"%alphanum%"	=   "%{DATA:[fieldname]}"
	"%id%"			=   "%{DATA:[fieldname]}"
	"%msgtime%"		= 	"%{DATA:[fieldname]}"
	"%time%"		=	"%{DATA:[fieldname]}"
	"%protocol%"	=	"%{DATA:[fieldname]}"
	"%msgid%" 		=   "%{DATA:[fieldname]}"
	"%severity%" 	=	"%{DATA:[fieldname]}"
	"%priority%" 	=	"%{DATA:[fieldname]}"
	"%apphost%" 	=	"%{DATA:[fieldname]}"
	"%appip%" 		=   "%{DATA:[fieldname]}"
	"%appvendor%"	=	"%{DATA:[fieldname]}"
	"%appname%" 	=	"%{DATA:[fieldname]}"
	"%srcdomain%"	=	"%{DATA:[fieldname]}"
	"%srczone%" 	= 	"%{DATA:[fieldname]}"
	"%srcipnat%" 	=	"%{DATA:[fieldname]}"
	"%srcportnat%" 	= 	"%{DATA:[fieldname]}"
	"%srcuser%" 	=  	"%{USER:[fieldname]}"
	"%srcuid%" 		=  	"%{UUID:[fieldname]}"
	"%srcuri%" 		=  	"%{URI:[fieldname]}"
	"%srcgid%" 		=  	"%{DATA:[fieldname]}"
	"%dstdomain%" 	= 	"%{DATA:[fieldname]}"
	"%dstzone%" 	=	"%{DATA:[fieldname]}"
	"%dstipnat%" 	= 	"%{DATA:[fieldname]}"
	"%dstportnat%" 	= 	"%{DATA:[fieldname]}"
	"%dstuser%" 	= 	"%{USER:[fieldname]}"
	"%dstuid%" 		= 	"%{UUID:[fieldname]}"
	"%dsturi%" 		=  	"%{URI:[fieldname]}"
	"%dstgroup%" 	= 	"%{DATA:[fieldname]}"
	"%dstgid%" 		= 	"%{DATA:[fieldname]}"
	"%dstemail%" 	= 	"%{EMAILADDRESS:[fieldname]}"
	"%iniface%" 	= 	"%{DATA:[fieldname]}"
	"%outiface%" 	= 	"%{DATA:[fieldname]}"
	"%policyid%" 	= 	"%{DATA:[fieldname]}"
	"%sessionid%" 	= 	"%{DATA:[fieldname]}"
	"%action%" 		= 	"%{DATA:[fieldname]}"
	"%command%" 	= 	"%{DATA:[fieldname]}"
	"%object%" 		= 	"%{DATA:[fieldname]}"
	"%method%" 		= 	"%{DATA:[fieldname]}"
	"%status%" 		= 	"%{LOGLEVEL:[fieldname]}"
	"%reason%" 		= 	"%{DATA:[fieldname]}"
	"%bytesrecv%" 	= 	"%{DATA:[fieldname]}"
	"%bytessent%" 	= 	"%{DATA:[fieldname]}"
	"%pktsrecv%" 	= 	"%{DATA:[fieldname]}"
	"%pktssent%" 	= 	"%{DATA:[fieldname]}"
	"%duration%" 	= 	"%{DATA:[fieldname]}"
	"%uri%"			=	"%{URI:[fieldname]}"

	[tags.delimitedstring]
    "\"\""		= 	"%{QUOTEDSTRING:[fieldname]}"
    "''"		= 	"%{QUOTEDSTRING:[fieldname]}"
    "<>"		=	"%{QUOTEDSTRING:[fieldname]}"
    "``"		=	"%{QUOTEDSTRING:[fieldname]}"

	
	#only need to add the tags here that you wish to change the name of, otherwise the sequence value is used.
	[tags.fieldname]
	"msgtime"	    =   "timestamp"
	"float"         =   "decimal"
	
